global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Nexus.Core;
global using Nexus.Core.Events;
global using Nexus.Graphics;
global using Nexus.Graphics.Cameras;
global using Nexus.Input;
