using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Security.Cryptography;
using Nexus.Assets.Fonts;

namespace Nexus.AssetPipeline;

/// <summary>Emits built-in font records directly from NAP's decoded manifest data.</summary>
public static class BuiltInFontGenerator
{
    /// <summary>Writes one generated C# file per face and a lazy lookup for built-in identifiers.</summary>
    public static void Generate(string manifestPath, string outputFolder)
    {
        using var manifest = JsonDocument.Parse(File.ReadAllBytes(manifestPath));
        var faces = new List<(string Id, string Class, FontRasterizerInput Input)>();
        foreach (var entry in manifest.RootElement.GetProperty("Fonts").GetProperty("Content").EnumerateObject())
        {
            if (!entry.Name.StartsWith("nexus.default.", StringComparison.Ordinal)) continue;
            if (!entry.Value.TryGetProperty("RasterizerInput", out var data))
                throw new InvalidDataException($"Font '{entry.Name}' has no RasterizerInput.");
            var input = JsonSerializer.Deserialize<FontRasterizerInput>(data.GetRawText())
                ?? throw new InvalidDataException($"Font '{entry.Name}' has null RasterizerInput.");
            var suffix = entry.Name["nexus.default.".Length..];
            if (suffix.Length == 0 || suffix.Any(c => !(c is >= 'a' and <= 'z' or '-')))
                throw new InvalidDataException($"Unsupported built-in identifier '{entry.Name}'.");
            var name = "Aileron" + string.Concat(suffix.Split('-').Select(word =>
                word.Length == 0 ? throw new InvalidDataException("Empty font name component.") : char.ToUpperInvariant(word[0]) + word[1..]));
            faces.Add((entry.Name, name, input));
        }
        if (faces.Count == 0) throw new InvalidDataException("No built-in rasterizer inputs were found.");
        Directory.CreateDirectory(outputFolder);
        foreach (var face in faces)
        {
            File.WriteAllText(Path.Combine(outputFolder, face.Class + ".g.cs"), EmitFace(face.Class, face.Input));
            PipelineLog.Info($"Generated {face.Id}: RasterizerInput SHA256={Convert.ToHexString(SHA256.HashData(JsonSerializer.SerializeToUtf8Bytes(face.Input)))}");
        }
        var lookup = new StringBuilder(Header("Nexus.Graphics.Text"));
        lookup.AppendLine("public static partial class BuiltInFonts\n{\n    /// <summary>Gets embedded decoded font data without reading a manifest or source font.</summary>\n    public static bool TryGetRasterizerInput(ContentId fontId, out FontRasterizerInput? input)\n    {\n        input = fontId.Value switch\n        {");
        foreach (var face in faces)
            lookup.AppendLine($"            {JsonSerializer.Serialize(face.Id)} => Generated.{face.Class}.Input,");
        lookup.AppendLine("            _ => null,\n        };\n        return input is not null;\n    }\n}");
        File.WriteAllText(Path.Combine(outputFolder, "BuiltInFontData.g.cs"), lookup.ToString());
    }

    private static string Header(string ns) => $"// <auto-generated />\n// Generated from RasterizerInput by nap generate-fonts. Do not edit.\n#nullable enable\nusing Nexus.Assets.Fonts;\n\nnamespace {ns};\n\n";
    private static string F(float value) => float.IsFinite(value) ? value.ToString("R", CultureInfo.InvariantCulture) + "f" : throw new InvalidDataException("Non-finite font coordinate.");
    private static string D(double value) => double.IsFinite(value) ? value.ToString("R", CultureInfo.InvariantCulture) + "d" : throw new InvalidDataException("Non-finite font value.");
    private static string Point(FontRasterizerPoint? point) => point is null ? "null" : $"new FontRasterizerPoint({F(point.X)}, {F(point.Y)})";

    private static string EmitFace(string name, FontRasterizerInput input)
    {
        var text = new StringBuilder(Header("Nexus.Graphics.Text.Generated"));
        text.AppendLine($"internal static class {name}\n{{\n    private static readonly Lazy<FontRasterizerInput> Data = new(Create);\n    internal static FontRasterizerInput Input => Data.Value;\n\n    private static FontRasterizerInput Create() => new(");
        var m = input.Metrics;
        text.AppendLine($"        new FontRasterizerMetrics({m.UnitsPerEm}, {m.Ascender}, {m.Descender}, {m.LineGap}, {m.GlyphCount}, {m.NumberOfHorizontalMetrics}, {m.IndexToLocFormat}),");
        var s = input.GenerationSettings;
        text.AppendLine($"        new FontRasterizerGenerationSettings({s.EmSize}, {D(s.DistanceRange)}, {s.Padding}),\n        new FontRasterizerGlyph[]\n        {{");
        for (var i = 0; i < input.Glyphs.Count; i++) text.AppendLine($"            Glyph{i}(),");
        text.AppendLine("        },\n        new TextKerningPair[]\n        {");
        foreach (var pair in input.Kerning)
            text.AppendLine($"            new TextKerningPair({pair.LeftCodepoint}, {pair.RightCodepoint}, {D(pair.AdvanceAdjustment)}),");
        text.AppendLine("        });");
        for (var i = 0; i < input.Glyphs.Count; i++)
        {
            var glyph = input.Glyphs[i];
            var bounds = glyph.Bounds is { } b ? $"new FontRasterizerBounds({F(b.Left)}, {F(b.Bottom)}, {F(b.Right)}, {F(b.Top)})" : "null";
            text.AppendLine($"\n    private static FontRasterizerGlyph Glyph{i}() => new(\n        {glyph.Codepoint}, {glyph.GlyphIndex}, {glyph.AdvanceWidth}, {glyph.LeftSideBearing}, {bounds},\n        new FontRasterizerContour[]\n        {{");
            foreach (var contour in glyph.Contours)
            {
                text.AppendLine("            new FontRasterizerContour(new FontRasterizerSegment[]\n            {");
                foreach (var segment in contour.Segments)
                    text.AppendLine($"                new FontRasterizerSegment({JsonSerializer.Serialize(segment.Kind)}, {Point(segment.Start)}, {Point(segment.Control)}, {Point(segment.End)}),");
                text.AppendLine("            }),");
            }
            text.AppendLine("        });");
        }
        text.AppendLine("}");
        return text.ToString();
    }
}
