<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>nap</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="StbImageSharp" />
    <ProjectReference Include="..\Graphics\Nexus.Graphics.csproj" />
    <ProjectReference Include="..\Assets\Nexus.Assets.csproj" />
  </ItemGroup>
</Project>
