<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Input" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexus.Audio\Nexus.Audio.csproj" />
    <ProjectReference Include="..\Nexus.Core\Nexus.Core.csproj" />
    <ProjectReference Include="..\Nexus.Graphics\Nexus.Graphics.csproj" />
    <ProjectReference Include="..\Nexus.Input\Nexus.Input.csproj" />
    <ProjectReference Include="..\Nexus.Physics\Nexus.Physics.csproj" />
  </ItemGroup>
</Project>
