<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Maths" />
    <PackageReference Include="Silk.NET.Windowing" />
    <ProjectReference Include="..\Nexus.Core\Nexus.Core.csproj" />
  </ItemGroup>
</Project>
