global using System;
global using System.Collections.Concurrent;
global using System.Collections.Immutable;
global using System.ComponentModel;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using Microsoft.Extensions.Logging;
global using Nexus.Core;
global using Nexus.Core.Performance;
global using Nexus.Graphics;
global using Nexus.Graphics.Cameras;
global using Nexus.Graphics.Components;
global using Nexus.Graphics.Geometry;
global using Nexus.Graphics.Shaders;
global using Nexus.Graphics.Textures;
global using Nexus.Graphics.Vulkan;
global using Nexus.Graphics.Vulkan.Buffers;
global using Nexus.Graphics.Vulkan.Components;
global using Nexus.Graphics.Vulkan.Pipelines;
global using Nexus.Graphics.Vulkan.Synchronization;
global using Silk.NET.Core.Native;
global using Silk.NET.Maths;
global using Silk.NET.Vulkan;
global using Silk.NET.Vulkan.Extensions.KHR;
global using Silk.NET.Windowing;
global using VkBuffer = Silk.NET.Vulkan.Buffer;
global using VkDescriptorPool = Silk.NET.Vulkan.DescriptorPool;
global using VkImage = Silk.NET.Vulkan.Image;
